# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b7c73591cde6be2abe2253c6d60960209b002d11ce19930f9b0c5284ed973f1d7fd25c01e4ef362b40297dd1b8fe1e73d12f497881d24d37f8585552d4e129d

test:
  secret_key_base: 630cc17f324a710bb35f1e9ee0ec3ec69e14c39bca6caf12c631e7b36c8ac7fdee1a4b734a635fb1ed05f4d100e61d9d85141a2800f3c7aee5eadebc30e4bb9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
